version: "3.8"
services:

  # Flask Application
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - 5000:5000
    image: app:flask
    container_name: flask_app
    command: python app.py runserver 0.0.0.0:5000
    




